### ISSUE TITLE
Result/Expected compliance with standard proposal

### ISSUE THREAD

**Issue by ilsken** [mnmlstc/core#37]
I know it was written before the proposal but is there any chance for bringing these two classes together into one and supporting the API from the proposal? Perhaps for V2?

**Comment by slurps-mad-rips** [comment]
This is planned for V2. The proposal is missing a few things (exception safety?) and also proposes some language changes to C++. Until then, you're unfortunately stuck with `expected<T>` and `result<T>`.

**Comment by slurps-mad-rips** [comment]
Hi! It's been a while since I looked at this issue. Due to some flux with the standard's committee (there hasn't been any progress that I can see regarding `expected<T, E>`) involving some papers to redefine the interface for `optional<T>` (to have a more cohesive interface with `variant<Ts...>` and `any`, I'm going to be closing this issue as it would be too difficult to hit a moving target.

Sorry for the inconvenience! At this point, I reckon if you need the proposal's usage you can use the Boost.Expected library itself, heavy handed as that might be.
