### ISSUE TITLE
variant get() function

### ISSUE THREAD

**Issue by hjanetzek** [mnmlstc/core#39]
It would be nice to have 'get' as member function of the variant template, instead of using core::get<N>(...). If I understood the documentation for  'auto get<N>() noexcept' correctly, it implies that is should actually be a member function:

    Depending on the value of *this (reference, const reference, rvalue) the type of the value returned will be affected as well.

**Comment by slurps-mad-rips** [comment]
Hi. `get` is provided as a non-member function to match the approach that Boost.Variant takes, as well as mirroring `std::tuple`, `std::pair`, `std::array`, and the `any_cast` approach used by `core::any`, Boost.Any, and `std::any`. A common approach for types such as these is to place any 'value' extraction in a non-member function.

Additionally, using get as a member function would make for some unnecessarily complex code if working with generic variants as one would have to write `v.template get<N>` or `v.template get<T>` in those situations.

Core's 1.1 documentation doesn't currently match master (which is effectively 1.2 alpha), and because of some health and self care issues I've not gotten around to finalizing the 1.2 release just yet (or making sure the documentation is accurate). The difference between the 1.1 and 1.2 documentation is quite large as sphinx-doc 1.3 now supports full declarations whereas some of the type declarations in 1.1 would break and not show correctly, and I did the best I could (also I got a little lazy near the end and failed to proof read a few things)

Apologies if this caused some confusion, but for the reasons stated above I won't be adding a member function that works like `get()`. The docs are undergoing a serious revamp however, and they should be more accurate and use better terminology.

**Comment by hjanetzek** [comment]
Thank you for the explanation! I still try to wrap my mind around the template basics - so I can't  follow the implied problems of ```get()``` being a member function. (Do you have a recommendation for a good reference to get started with templates?)

The issue was mainly aesthetically to me but also 'core' as namespace could easily be confused with the existing 'core' module of the project in which I started to use your variant - and flyweight.

**Comment by slurps-mad-rips** [comment]
With respect to the namespace confusion issue, there is a solution there if you want. Because MNMLSTC Core uses an inline namespace, everything is actually contained within `core::v1` (but the `v1` is optional). So what you can do is alias the `v1` namespace to some other name. e.g., `namespace mnmlstc = core::v1` (or something like that :smile:)

As for giving a better reference for templates, I'd recommend taking a look at everything listed under "Templates" [here](http://en.cppreference.com/w/cpp/language). It won't explain the *why* of everything but should give a good overview on some of the rules and when behavior changed between standard versions :smile:
