### ISSUE TITLE
string_view::max_size() is doesn't match the standard (revision 7)

### ISSUE THREAD

**Issue by vmrob** [mnmlstc/core#46]
I was unable to find a revision of the `string_view` proposal past [revision 7](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3921.html), but the text for `max_size` in rev 7 is as follows:

>`constexpr size_type max_size() const noexcept`
>Returns: The largest possible number of char-like objects that can be referred to by a basic_string_view.

This implementation currently only returns the size of the current string view which is different from the standard library implementation provided on my machine (`Apple LLVM version 7.0.2 (clang-700.1.81)`).

I believe it should return `::std::numeric_limits::<size_type>::max()` instead.

**Comment by slurps-mad-rips** [comment]
Hi, sorry for the delay in a response. I've been dealing with personal issues that have prevented me from responding to filed tickets. This does appear to be the correct behavior, and is probably a copy-paste bug that no one has caught until now because, really, how often does max_size get used compared to size?

It'll be taken care of next time I make a push.
