### ISSUE TITLE
SEGV when using small types that are not noexcept copy constructable

### ISSUE THREAD

**Issue by Eyenseo** [mnmlstc/core#47]
Hello,

this is a bug in `any` / `dispatch`.

Types that are not noexcept copy constructable are treated by `dispatch` as not small, but their value is stored in the pointer of `any` like a small type. When applying `any_cast` to such an `any` instance a SEGV occurs as the __value__ is interpreted as the __address__ to the value.

Please see the following test case:
```cpp
TEST_CASE("small-assignment", "[assignment]") {
  struct Foo {
    int f_;

    Foo()
        : f_(0) {
    }
    Foo(const Foo& other)
        : f_(other.f_) {
    }
    Foo(Foo&& other) {
      swap(*this, other);
    }

    Foo& operator=(Foo other) {
      swap(*this, other);
      return *this;
    }

    void swap(Foo& first, Foo& second) {
      if(&first != &second) {
        using std::swap;

        swap(first.f_, second.f_);
      }
    }
  };

  // not small because not noexcept
  CHECK_FALSE(::core::impl::is_small<Foo>::value);

  int f = 42;
  Foo foo;
  foo.f_ = f;

  CHECK(f == foo.f_);

  core::any a = foo;

  CHECK(f == foo.f_);
  CHECK(f == core::any_cast<Foo>(a).f_);  // Seg fault - the address (this) of
                                          // the temporary object has a value of
                                          // 0x2A (42)

  core::any b = a;

  CHECK(f == foo.f_);
  CHECK(f == core::any_cast<Foo>(a).f_);
  CHECK(f == core::any_cast<Foo>(b).f_);

  core::any c = std::move(a);

  CHECK(f == foo.f_);
  CHECK(0 == core::any_cast<Foo>(a).f_);
  CHECK(f == core::any_cast<Foo>(b).f_);
  CHECK(f == core::any_cast<Foo>(c).f_);
}
```

**Comment by slurps-mad-rips** [comment]
This is without a doubt one of, if not THE, dumbest bug I've ever run into.
luckily it's an easy fix you can apply to your local branch until I can push up something more permanent. It is also really dumb that I let this slip past me.. What's happening here is that we're asking `is_small` if `Foo` is or not. Unfortunately, the any type is actually asking (in the case of `core::any a = foo`) if `Foo&` `is_small`, which does return true because for some `is_nothrow_copy_constructible` says that all references are noexcept when copying (ignoring the type system and how they actually interact apparently).

To fix this, just change the line 28 in any.hpp to read:

```cpp
::std::is_nothrow_copy_constructible<decay_t<T>>::value
```

and you'll be good to go.

**Comment by Eyenseo** [comment]
Thank you for the reply and solution :+1:
