### ISSUE TITLE
Future releases?

### ISSUE THREAD

**Issue by kevinAlbs** [mnmlstc/core#59]
Hi, are there any future releases planned? For our case, it'd be nice to have the fix to https://github.com/mnmlstc/core/pull/23 without building from master.

Thank you!
Kevin

**Comment by bruxisma** [comment]
Hi,

Unsure if this is still relevant for you, however I don't believe MNMLSTC Core will ever see a second release anytime soon. Time, life, and a series of unfortunate events resulted in it getting away from me. It would need an extremely huge overhaul to get the code quality back to where it needs to be. In fact, there's a high chance I might have to shutter MNMLSTC in the near future due to personal financial issues (unless someone were to offer a buyout)

It became extremely difficult to implement C++17 features in C++11, and with so many shops finally moving to it, its use is (I would argue) diminishing. That said, I am currently working on a spiritual successor to core, though its minimum is C++17, and its features are drastically different, given how much has happened in the C++ space in recent years.

I'm terribly sorry for the inconvenience and also not responding to your issue in a timely manner.
